### ISSUE TITLE
how to  control the strength  of  brightening  the image ,find the result is little over-exposure,

### ISSUE THREAD

**Issue by msk7131** [OoiXinPeng/LLDE#2]
how to  control the strength  of  brightening  the image ,find the result is little over-exposure,and  the result is unstable

**Comment by OoiXinPeng** [comment]
- Currently, there is no method to control the level of exposure.
- To consistently produce the same enhanced image across multiple runs, manually set the random seeds in NumPy and PyTorch before enhancing the specific low-light image.
